ALTER TABLE chunks ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE chunks ADD COLUMN ttl_seconds INTEGER NOT NULL DEFAULT 604800;
ALTER TABLE pending_chunks ADD COLUMN ttl_seconds INTEGER NOT NULL DEFAULT 604800;
