/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/killbane1232/huginn-messenger */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bridge.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern long messenger_create(char* username, char* muninnAddr, char* dbPath, char* chunkTTL, char* turnAddr, char* turnUser, char* turnPass);
extern void messenger_destroy(long handle);
extern char* messenger_get_me(long handle);
extern char* messenger_get_peers(long handle);
extern char* messenger_search_peers(long handle, char* query);
extern char* messenger_get_messages(long handle, char* peerID);
extern char* messenger_send_message(long handle, char* to, char* text, int ttl);
extern char* messenger_send_file(long handle, char* to, char* text, char* filePath, int ttl);
extern char* messenger_get_config(long handle);
extern char* messenger_save_config(long handle, char* jsonConfig);
extern char* messenger_get_event(long handle, int timeoutMs);
extern char* messenger_get_downloads_dir(long handle);
extern char* messenger_get_file_path(long handle, char* fileID);
extern int messenger_is_peer_online(long handle, char* peerID);
extern void messenger_free_string(char* s);

#ifdef __cplusplus
}
#endif
